=== ANR2ME/spec/schema-validator/schemas/header.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "",
    "definitions": {
    	"bucket_date": {
			"type": "string",
			"pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
		},
		"semantic_version": {
			"type": "string",
			"pattern": "^[0-9]+.[0-9]+.[0-9]+$"
		},
		"uuid-v4": {
			"type": "string",
			"pattern": "[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\Z"
		},
		"ip-address": {
			"format": "ipv4"
		},
		"test-version": {
			"type": "string",
			"pattern": "[0-9]+.[0-9]+"
		},
		"date-time": {
			"type": "string",
			"patter": "[0-9]{4}-[0-9]{1,2}-[0-9]{1,2} [0-9]{2}:[0-9]{2}:[0-9]{2}"
		}
    },
    "properties": {
    	"bucket_date": { "$ref": "#/definitions/bucket_date" },
    	"data_format_version": { "$ref": "#/definitions/semantic_version" },
    	"id": { "$ref": "#/definitions/uuid-v4" },
    	"input": { "$ref": "#/definitions/ip-address" },
    	"options": { "type": "array" },
    	"probe_asn": { "type": "string" },
		"probe_cc": { "type": "string" },
		"probe_ip": { "$ref": "#/definitions/ip-address" },
		"report_filename": { "type": "string" },
		"report_id": { "type": "string" },
		"software_name": { "type": "string", "enum": [ "ooniprobe" ] },
		"software_version": { "$ref": "#/definitions/semantic_version" },
		"test_helpers": { "type": "object" },
		"input_hashes": { "type": "array" },
		"probe_city": { "type": [ "null", "string" ] },
		"backend_version": { "$ref": "#/definitions/semantic_version" },
		"test_name": { "type": "string" },
		"test_runtime": { "type": "number" },
		"test_start_time": { "$ref": "#/definitions/date-time" },
		"test_version": { "$ref": "#/definitions/test-version" },
		"test_keys": { "type": "object" }
    }
}

=== ANR2ME/spec/schema-validator/test-specs/ts-004-http-host.json
{
	"bucket_date": "2015-11-25",
	"data_format_version": "0.2.0",
	"id": "a59899ab-cd33-49db-8ca4-7bf5dd2d317d",
	"input": null,
	"options": [],
	"probe_asn": "AS3269",
	"probe_cc": "IT",
	"probe_ip": "127.0.0.1",
	"report_filename": "2015-11-25/20151125T214003Z-IT-AS3269-http_host-FKByhJTXzseUDZOSvQkPiZur0ji6csV5UCiyarEoCCUCiKicGTgXq06fcJVA6XfA-0.1.0-probe.json",
	"report_id": "FKByhJTXzseUDZOSvQkPiZur0ji6csV5UCiyarEoCCUCiKicGTgXq06fcJVA6XfA",
	"software_name": "ooniprobe",
	"software_version": "1.3.2",
	"test_helpers": {
		"backend": "http://216.156.197.144:80"
	},
	"input_hashes": [],
	"probe_city": null,
	"backend_version": "1.1.4",
	"test_keys": {
		"agent": "agent",
		"filtering_prepend_newline_to_method": false,
		"requests": [
			{
				"request": {
					"body": null,
					"headers": {
						"Host": null
					},
					"method": "GET",
					"tor": {
						"exit_ip": false,
						"exit_name": false,
						"is_tor": false
					},
					"url": "http://216.156.197.144:80"
				},
				"response": {
					"body": "{\"headers_dict\": {\"Connection\": [\"close\"], \"Host\": [\"None\"]}, \"request_line\": \"GET / HTTP/1.1\", \"request_headers\": [[\"Connection\", \"close\"], [\"Host\", \"None\"]]}",
					"code": 200,
					"headers": {}
				},
				"response_length": null
			},
			{
				"request": {
					"body": null,
					"headers": {
						"Host": null
					},
					"method": "\nGET",
					"tor": {
						"exit_ip": false,
						"exit_name": false,
						"is_tor": false
					},
					"url": "http://216.156.197.144:80"
				},
				"response": {
					"body": "{\"headers_dict\": {\"Connection\": [\"close\"], \"Host\": [\"None\"]}, \"request_line\": \"\\nGET / HTTP/1.1\", \"request_headers\": [[\"Connection\", \"close\"], [\"Host\", \"None\"]]}",
					"code": 200,
					"headers": {}
				},
				"response_length": null
			}
		],
		"send_host_header": false,
		"socksproxy": null,
		"start_time": 1448484003.0,
		"transparent_http_proxy": false
	},
	"test_name": "http_host",
	"test_runtime": 0.3475949764,
	"test_start_time": "2015-11-25 21:40:03",
	"test_version": "0.2.4"
}

=== ANR2ME/spec/schema-validator/test-specs/ts-002-dns-consistency.json
{
	"bucket_date": "2015-11-23",
	"data_format_version": "0.2.0",
	"id": "e6f6257f-e7c2-48fa-8345-b7ed055ab1d2",
	"input": "198.175.124.185",
	"options": [
		"-f",
		"citizenlab-urls-global.txt",
		"-T",
		"dns-server-jo.txt"
	],
	"probe_asn": "AS8376",
	"probe_cc": "JO",
	"probe_ip": "127.0.0.1",
	"report_filename": "2015-11-23/20151123T161428Z-JO-AS8376-dns_consistency-F1KI1WusW4c1T6OGyQDgHJjaSQ1bfpqV2G39bpmuHiLAJnse8R1F44vdRuTz6nO4-0.1.0-probe.json",
	"report_id": "F1KI1WusW4c1T6OGyQDgHJjaSQ1bfpqV2G39bpmuHiLAJnse8R1F44vdRuTz6nO4",
	"software_name": "ooniprobe",
	"software_version": "1.3.1",
	"test_helpers": {
		"backend": "8.8.8.8:53"
	},
	"input_hashes": [
		"0055f0881fba857d8b48123017d7aec83014e89f057e44b66107f657ec5e2eab"
	],
	"probe_city": null,
	"backend_version": "1.1.4",
	"test_keys": {
		"control_resolver": "8.8.8.8:53",
		"errors": {
			"212.118.0.1": "no_answer",
			"212.118.0.2": "no_answer",
			"212.38.128.3": "dns_lookup_error",
			"217.144.6.6": "no_answer",
			"8.8.8.8:53": "no_answer",
			"80.90.160.135": "dns_lookup_error",
			"80.90.160.172": "dns_lookup_error",
			"81.28.112.2": "dns_lookup_error"
		},
		"failed": [
			"80.90.160.172",
			"8.8.8.8:53",
			"212.118.0.2",
			"80.90.160.135",
			"212.38.128.3",
			"212.118.0.1",
			"217.144.6.6",
			"81.28.112.2"
		],
		"inconsistent": [],
		"queries": [
			{
				"answers": [],
				"failure": "no_answer",
				"hostname": "198.175.124.185",
				"query_type": "A",
				"resolver_hostname": "8.8.8.8",
				"resolver_port": 53
			},
			{
				"answers": [],
				"failure": "deferred_timeout_error",
				"hostname": "198.175.124.185",
				"query_type": "A",
				"resolver_hostname": "212.38.128.3",
				"resolver_port": 53
			},
			{
				"answers": [],
				"failure": "no_answer",
				"hostname": "198.175.124.185",
				"query_type": "A",
				"resolver_hostname": "217.144.6.6",
				"resolver_port": 53
			},
			{
				"answers": [],
				"failure": "deferred_timeout_error",
				"hostname": "198.175.124.185",
				"query_type": "A",
				"resolver_hostname": "81.28.112.2",
				"resolver_port": 53
			},
			{
				"answers": [],
				"failure": "deferred_timeout_error",
				"hostname": "198.175.124.185",
				"query_type": "A",
				"resolver_hostname": "80.90.160.135",
				"resolver_port": 53
			},
			{
				"answers": [],
				"failure": "deferred_timeout_error",
				"hostname": "198.175.124.185",
				"query_type": "A",
				"resolver_hostname": "80.90.160.172",
				"resolver_port": 53
			},
			{
				"answers": [],
				"failure": "no_answer",
				"hostname": "198.175.124.185",
				"query_type": "A",
				"resolver_hostname": "212.118.0.1",
				"resolver_port": 53
			},
			{
				"answers": [],
				"failure": "no_answer",
				"hostname": "198.175.124.185",
				"query_type": "A",
				"resolver_hostname": "212.118.0.2",
				"resolver_port": 53
			}
		],
		"start_time": 1448291668,
		"successful": []
	},
	"test_name": "dns_consistency",
	"test_runtime": 0.0837070942,
	"test_start_time": "2015-11-23 16:14:28",
	"test_version": "0.6"
}

=== ANR2ME/spec/schema-validator/test-specs/ts-008-tcp-connect.json
{
	"bucket_date": "2015-12-29",
	"data_format_version": "0.2.0",
	"id": "6305de45-ce5d-43b5-ba11-fd9019e5e90c",
	"input": "github.com:443\n",
	"input_hashes": [
		"586ded3d64bcb8672fedb475c8ea799331779b446e529b204a2088bedc91e3f0"
	],
	"options": [
		"-f",
		"hosts.txt"
	],
	"probe_asn": "AS13703",
	"probe_cc": "US",
	"probe_ip": "127.0.0.1",
	"report_filename": "2015-12-29/20151225T201931Z-US-AS13703-tcp_connect-IHsje0cnGs2uOpRgEmfnkpuZAa8ysrZgdf8YyImTUhtBTSZSoTeXle79RuchYuzi-0.1.0-probe.json",
	"report_id": "IHsje0cnGs2uOpRgEmfnkpuZAa8ysrZgdf8YyImTUhtBTSZSoTeXle79RuchYuzi",
	"software_name": "ooniprobe",
	"software_version": "1.3.1",
	"backend_version": "1.1.4",
	"probe_city": null,
	"test_helpers": {},
	"test_keys": {
		"connection": "success"
	},
	"test_name": "tcp_connect",
	"test_runtime": 0.0218939781,
	"test_start_time": "2015-12-25 20:19:31",
	"test_version": "0.1"
}

=== ANR2ME/spec/schema-validator/test-specs/ts-003-http-requests.json
{
	"bucket_date": "2015-11-22",
	"data_format_version": "0.2.0",
	"id": "07873c37-9441-47e3-93b8-94db10444c64",
	"input": "http://googleusercontent.com/",
	"options": [
		"-f",
		"37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1"
	],
	"probe_asn": "AS0",
	"probe_cc": "CH",
	"probe_ip": "127.0.0.1",
	"report_filename": "2015-11-22/20151122T103202Z-CH-AS0-http_requests-XsQk40qrhgvJEdbXAUFzYjbbGCBuEsc1UV5RAAFXo4hysiUo3qyTfo4NTr7MjiwN-0.1.0-probe.json",
	"report_id": "XsQk40qrhgvJEdbXAUFzYjbbGCBuEsc1UV5RAAFXo4hysiUo3qyTfo4NTr7MjiwN",
	"software_name": "ooniprobe",
	"software_version": "1.3.1",
	"test_helpers": {},
	"backend_version": "1.1.4",
	"input_hashes": [
		"37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1"
	],
	"probe_city": null,
	"test_name": "http_requests",
	"test_runtime": 0.1842639446,
	"test_start_time": "2015-11-22 10:32:02",
	"test_version": "0.2.4",
	"test_keys": {
		"agent": "agent",
		"body_length_match": null,
		"body_proportion": null,
		"control_failure": "socks_host_unreachable",
		"experiment_failure": "dns_lookup_error",
		"factor": 0.8,
		"headers_diff": null,
		"headers_match": null,
		"requests": [
			{
				"failure": "dns_lookup_error",
				"request": {
					"body": null,
					"headers": {
						"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; de; rv:1.9.2) Gecko/20100115 Firefox/3.6"
					},
					"method": "GET",
					"tor": {
						"exit_ip": false,
						"exit_name": false,
						"is_tor": false
					},
					"url": "http://googleusercontent.com/"
				},
				"response": {
					"body": null,
					"headers": {}
				},
				"response_length": null
			},
			{
				"failure": "socks_host_unreachable",
				"request": {
					"body": null,
					"headers": {
						"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.7) Gecko/20091221 Firefox/3.5.7"
					},
					"method": "GET",
					"tor": {
						"exit_ip": null,
						"exit_name": null,
						"is_tor": true
					},
					"url": "http://googleusercontent.com/"
				},
				"response": {
					"body": null,
					"headers": {}
				},
				"response_length": null
			},
			{
				"failure": "dns_lookup_error",
				"request": {
					"body": null,
					"headers": {
						"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; de; rv:1.9.2) Gecko/20100115 Firefox/3.6"
					},
					"method": "GET",
					"tor": {
						"exit_ip": null,
						"exit_name": null,
						"is_tor": false
					},
					"url": "http://googleusercontent.com/"
				},
				"response": {
					"body": null,
					"headers": {}
				},
				"response_length": null
			},
			{
				"failure": "dns_lookup_error",
				"request": {
					"body": null,
					"headers": {
						"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; de; rv:1.9.2) Gecko/20100115 Firefox/3.6"
					},
					"method": "GET",
					"tor": {
						"exit_ip": null,
						"exit_name": null,
						"is_tor": false
					},
					"url": "http://googleusercontent.com/"
				},
				"response": {
					"body": null,
					"headers": {}
				},
				"response_length": null
			},
			{
				"failure": "socks_host_unreachable",
				"request": {
					"body": null,
					"headers": {
						"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; de; rv:1.9.2) Gecko/20100115 Firefox/3.6"
					},
					"method": "GET",
					"tor": {
						"exit_ip": null,
						"exit_name": null,
						"is_tor": true
					},
					"url": "http://googleusercontent.com/"
				},
				"response": {
					"body": null,
					"headers": {}
				},
				"response_length": null
			},
			{
				"failure": "socks_host_unreachable",
				"request": {
					"body": null,
					"headers": {
						"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; de; rv:1.9.2) Gecko/20100115 Firefox/3.6"
					},
					"method": "GET",
					"tor": {
						"exit_ip": null,
						"exit_name": null,
						"is_tor": true
					},
					"url": "http://googleusercontent.com/"
				},
				"response": {
					"body": null,
					"headers": {}
				},
				"response_length": null
			}
		],
		"socksproxy": null,
		"start_time": 1448184722.0
	}
}
